apiVersion: v1
kind: Service
metadata:
  name: broker-amq-amqp
  labels:
    ActiveMQArtemis: spring-boot-camel-amq
spec:
  selector:
    ActiveMQArtemis: spring-boot-camel-amq
  ports:
    - name: amqps
      protocol: TCP
      port: 5671
      targetPort: 5671
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
